### PR TITLE
Scaffold

### PR DESCRIPTION
**Pull request by mattlangan**

### CODE REVIEW

**Comment by mattlangan** [comment]
@amenity Please review and merge at your convenience. The compiled `_site/` is published at https://site-jipfnijygq.now.sh

Once this is merged in I'll quickly follow-up with a separate PR that handles the AWS + Travis CI automation.

**Comment by amenity** [comment]
This is looking _really_ excellent. I appreciate all this work and can't wait till it gets the new-Zilker-✨ ... 

**Identifying**
Under _High leverage_ I think it might be good to add some advice on reaching out to other departments to see if they might need the same service. Partnering like this has the benefit of sharing costs and, for in-house solutions, developer resources. Additionally, reaching out to both other cities/organizations who have similar needs/tools is really informative. 

FWIW, under _Vendor_ I was imagining recommending:
- Requirements gathering
- Competitive analysis in matrix, a la [CoA Third Party Tool Assessment](https://docs.google.com/spreadsheets/d/1dTPj9wO1Nf0mltj8e6xCzeHk_zNHrvT3kDHhULbs4lw/edit#gid=342954861) or our [form comparison sheet](https://docs.google.com/spreadsheets/d/1ov27dpfaFW9nk0mVIpshj5Sj5mxoKaQafk8W4oyvqws/edit#gid=0). It would be nice to polish up a spreadsheet template as a resource. 

Something similar under _In-house_ but including resources like [Code.gov](https://code.gov/#/). 

**Criteria**
I would add _Scalability_:
- Well-defined quantitative and qualitative growth scales
Well-defined quantitative and qualitative growth scales
- Identification of resource bottlenecks and requirements
- Careful, accurate capacity planning
- Scalable handling of traffic
- The scaling of dependencies
- Scalable data storage

This is [snagged directly from the Susan Fowler book on production-readiness](https://books.google.com/books?id=-_OeDQAAQBAJ&pg=PA31&lpg=PA31&dq=%22Well-defined+quantitative+and+qualitative+growth+scales%22&source=bl&ots=n8WAblqE0R&sig=_X0LSe0Tdh44TfpkB8Qvkbn_xNw&hl=en&sa=X&ved=0ahUKEwjN2O-h-ujVAhXCPY8KHSwRDlkQ6AEIKDAA#v=onepage&q=%22Well-defined%20quantitative%20and%20qualitative%20growth%20scales%22&f=false). She also points out that SLAs regarding uptime/availability are the most commonly used method of measuring a service's success and an explanation of nines notation. Some of this is included in the [abridged PDF](http://feederio.com/files/book/14882924455493_c8173badfee4e0c3749dd7124ed3cb7d.pdf).

**Comment by mattlangan** [comment]
@amenity not sure why this was closed. Do you want those additions to go in before this branch is merged or can they be done in a separate branch + pr?
This current state is just meant to be a starting point that gets extended upon over the next days & weeks. I just wanted to get `master` updated with something deployable so we can start doing deployments from there.

**Comment by amenity** [comment]
No, so sorry - was rushing.

**Comment by amenity** [comment]
Can totally me done in a separate branch; go ahead and merge.

**Review by amenity — APPROVED** [review]
Excellent.

**Pull request merged**
